name: sv_CI
on:
  push:
  pull_request:
jobs:
  sv-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y verilator

      - name: Compile testbench
        run: |
          verilator --binary -sv \
            -I src/design \
            --top-module testbench \
            src/design/common.sv \
            src/design/alu.sv \
            src/design/control.sv \
            src/design/data_memory.sv \
            src/design/program_memory.sv \
            src/design/register_file.sv \
            src/design/fetch_stage.sv \
            src/design/decode_stage.sv \
            src/design/execute_stage.sv \
            src/design/mem_stage.sv \
            src/design/uart.sv \
            src/design/cpu.sv \
            src/simulation/testbench.sv \
            -o obj_dir/simulate

      - name: Run simulation
        run: ./obj_dir/simulate
