name: sv_CI
on: [push, pull_request]

jobs:
  sv-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y verilator

#      - name: Debug
#        run: |
#          echo "=== common.sv ==="
#          cat src/design/common.sv
#          echo "=== cpu.sv ==="
#          cat src/design/cpu.sv
#W          
#     - name: Check verilator version
#        run: verilator --version
        
      - name: Compile testbench
        run: |
          mkdir -p obj_dir
          verilator --binary -sv -Wno-fatal --top-module testbench src/design/common.sv src/design/alu.sv src/design/mdu.sv src/design/control.sv src/design/data_memory.sv src/design/forwarding.sv src/design/program_memory.sv src/design/register_file.sv src/design/fetch_stage.sv src/design/decode_stage.sv src/design/execute_stage.sv src/design/mem_stage.sv src/design/uart.sv src/design/uart_data.sv src/design/cpu.sv src/simulation/testbench.sv -o simulate
          echo "=== files in root ==="
          ls -la
          echo "=== files in obj_dir ==="
          ls -la obj_dir/

      - name: Run simulation
        run: cd src/design && ../../obj_dir/simulate
